server:
  port: 8100

spring:
  cloud:
    discovery:
      enabled: true
  application:
    name: user-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${USER_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

google:
  client-id: ${GOOGLE_CLIENT_ID}

springdoc:
  swagger-ui:
    tags-sorter: alpha

services:
  auction-service:
    name: auction-service
    url: http://localhost:8300
  order-service:
    name: order-service
    url: http://localhost:8500
  product-service:
    name: product-service
    url: http://localhost:8400