
services:
  gateway-service:
    image: bidket/gateway-service:${GATEWAY_IMAGE_TAG}
    container_name: gateway-service
    ports:
      - "${GATEWAY_PORT}:8000"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod

      # infra EC2 eureka로 연결
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

    restart: unless-stopped
    networks:
      - bidket-app-net

  user-service:
    image: bidket/user-service:${USER_IMAGE_TAG}
    container_name: user-service
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # JWT
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_TOKEN_EXPIRATION=${JWT_ACCESS_TOKEN_EXPIRATION}
      - JWT_REFRESH_TOKEN_EXPIRATION=${JWT_REFRESH_TOKEN_EXPIRATION}

      # DB (user-service)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - USER_DB=${USER_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
        - bidket-app-net

  product-service:
    image: bidket/product-service:${PRODUCT_IMAGE_TAG}
    container_name: product-service
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # DB (product-service)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - PRODUCT_DB=${PRODUCT_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: unless-stopped
    networks:
      - bidket-app-net

  order-service:
    image: bidket/order-service:${ORDER_IMAGE_TAG}
    container_name: order-service
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # DB (order-service)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ORDER_DB=${ORDER_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        
      # Kafka
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      # Order Event Types
      - EVENT_TYPE_ORDER_CREATED=${EVENT_TYPE_ORDER_CREATED}
      - EVENT_TYPE_ORDER_CANCELLED=${EVENT_TYPE_ORDER_CANCELLED}
    restart: unless-stopped
    networks:
      - bidket-app-net

  auction-service:
    image: bidket/auction-service:${AUCTION_IMAGE_TAG}
    container_name: auction-service
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # DB (auction-service)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - AUCTION_DB=${AUCTION_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      # Kafka
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      # Auction Event Types
      - EVENT_TYPE_AUCTION_CREATED=${EVENT_TYPE_AUCTION_CREATED}
      - EVENT_TYPE_AUCTION_STARTED=${EVENT_TYPE_AUCTION_STARTED}
      - EVENT_TYPE_AUCTION_ENDED=${EVENT_TYPE_AUCTION_ENDED}
      - EVENT_TYPE_AUCTION_CANCELLED=${EVENT_TYPE_AUCTION_CANCELLED}
      - EVENT_TYPE_AUCTION_PRICE_UPDATED=${EVENT_TYPE_AUCTION_PRICE_UPDATED}

      # Bid Event Types
      - EVENT_TYPE_BID_PLACED=${EVENT_TYPE_BID_PLACED}
      - EVENT_TYPE_BID_CANCELLED=${EVENT_TYPE_BID_CANCELLED}
      - EVENT_TYPE_BID_OUTBID=${EVENT_TYPE_BID_OUTBID}
      - EVENT_TYPE_BID_WON=${EVENT_TYPE_BID_WON}
      - EVENT_TYPE_HIGHEST_BID_CHANGED=${EVENT_TYPE_HIGHEST_BID_CHANGED}
    restart: unless-stopped
    networks:
      - bidket-app-net

  notification-service:
    image: bidket/notification-service:${NOTIFICATION_IMAGE_TAG}
    container_name: notification-service
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # Slack Webhook
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}

      # Email
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # DB (notification-service)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - NOTIFICATION_DB=${NOTIFICATION_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}

      # Kafka
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      # Notification Event Types
      - EVENT_TYPE_SEND_NOTIFICATION=${EVENT_TYPE_SEND_NOTIFICATION}
    restart: unless-stopped
    networks:
      - bidket-app-net

  queue-service:
    image: bidket/queue-service:${QUEUE_IMAGE_TAG}
    container_name: queue-service
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_SERVER_URL=${EUREKA_SERVER_URL}

      # JWT
      - JWT_SECRET=${JWT_SECRET}

      # Queue service active token
      - ACTIVE_TOKEN_SECRET=${ACTIVE_TOKEN_SECRET}
      - ACTIVE_TOKEN_EXPIRATION=${ACTIVE_TOKEN_EXPIRATION}

      # DB (queue-service)
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - QUEUE_DB=${QUEUE_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

      # Kafka
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      # Redis
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    restart: unless-stopped
    networks:
      - bidket-app-net

networks:
  bidket-app-net:
    driver: bridge
