server:
  port: 8500

spring:
  application:
    name: order-service
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${ORDER_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      host: localhost
      port: 6379

services:
  auction:
    base-url: http://localhost:8300

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

# Order Service Kafka Topics
# 명명 규칙: [소비_도메인].[생산_도메인]
order:
  kafka:
    topics:
      # Auction이 생산, Order가 소비
      order-auction: order.auction
      # Order가 생산, Auction이 소비
      auction-order: auction.order

# OutBox 폴링 설정
outbox:
  publisher:
    fixed-delay-ms: 5000  # 5초마다 폴링