server:
  port: 8400

spring:
  application:
    name: queue-service
  config:
    import: optional:file:.env[.properties]
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${QUEUE_DB:bidket_queue}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SEVER:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: queue-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

active_token:
  secret: ${ACTIVE_TOKEN_SECRET}
  expired_at: ${ACTIVE_TOKEN_EXPIRATION}

heartbeat:
  frequency: 5

kafka:
  notification:
    queue:
      admitted:
        topic: notification.queue.admitted
        partition: 3
        replicas: 1
        retention: 8400
      near_turn:
        topic: notification.queue.near_turn
        partition: 3
        replicas: 1
        retention: 8400
  auction:
    topic: queue.auction

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true